import { type NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import Calendar from "@/components/calendar.tsx"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Booking Software</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
        
        <main>
          <Calendar />
        </main>
    </>
  )
}

export default Home
