import { type NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import Calendar from "@/components/calendar.tsx"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <main>
        <h1>aden</h1> 
        <Calendar />
      </main>
    </>
  )
}

export default Home
